import os
import numpy as np

TARGET_COLUMN="Result"
PIPELINE_NAME="NetworkSecurity"
ARTIFACT_DIR="Artifacts"
FILE_NAME="networkData.csv"

TRAIN_FILE_NAME="train.csv"
TEST_FILE_NAME="test.csv"

SCHEMA_FILE_PATH=os.path.join("data_schema","schema.yaml")
SAVED_MODEL_DIR=os.path.join("")
MODEL_FILE_NAME="model.pkl"


#Data Ingestion

DATA_INGESTION_COLLECTION_NAME="NetworkData"
DATA_INGESTION_DATABASE_NAME="JayrajAI"
DATA_INGESTION_INGESTED_DIR="ingested"
DATA_INGESTION_FEATURE_STORE="feature_store"
DATA_INGESTION_DIR_NAME="data_ingestion"
DATA_INGESTION_TRAIN_TEST_RATIO=0.2

#Data Validation

DATA_VALIDATION_DIR_NAME="data_validation"
DATA_VALIDATION_VALID_DIR="valid"
DATA_VALIDATION_INVALID_DIR="invalid"
DATA_VALIDATION_DRIFT_REPORT_DIR="drift_report"
DATA_VALIDATION_DRIFT_REPORT_FILE_NAME="report.yaml"
PREPROCESSING_OBJECT_FILE_NAME="proprocessing.pkl"

#Data Transformation

DATA_TRANSFORMATION_DIR_NAME="data_transformation"
DATA_TRANSFORMATION_TRANSFORMED_DATA_DIR="transformed"
DATA_TRANSFORMATION_TRANSFORMED_OBJECT_DIR="transformed_object"
DATA_TRANSFORMATION_IMPUTER_PARAMS={
    "missing_values":np.nan,
    "n_neighbors":3,
    "weights":"uniform"
}
DATA_TRANSFORMATION_TRAIN_FILE_PATH="train.npy"
DATA_TRANSFORMATION_TEST_FILE_PATH="test.npy"

# Model Trainer

MODEL_TRAINER_DIR_NAME="model_trainer"
MODEL_TRAINER_TRAINED_MODEL_DIR="trained_model"
MODEL_TRAINER_TRAINED_MODEL_NAME="model.pkl"
MODEL_TRAINER_EXPECTED_SCORE=0.6
MODEL_TRAINER_OVER_FITTING_UNDER_FITTING_THRESHOLD=0.05

TRAINING_BUCKET_NAME="networksecurity-jayraj-nicky"